# {{ generated_tag }}

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000

DEFAULT_USER=jeremie
ZSH=/usr/share/oh-my-zsh/
ZSH_THEME="agnoster"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"

plugins=(
  colored-man-pages
  colorize
  git
  git-extras
  gradle
  httpie
  mvn
  npm
  nvm
  pip
  rvm
  vagrant
)

ZSH_CACHE_DIR=$HOME/.oh-my-zsh-cache
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

source $ZSH/oh-my-zsh.sh
source ~/.nvm/nvm.sh
source ~/.rvm/scripts/rvm

alias ansible-activate=". /opt/ansible/bin/activate"

# enable direnv
eval "$(direnv hook zsh)"

# enable sdkman
if [ -f $HOME/.sdkman/bin/sdkman-init.sh ] ; then
  source $HOME/.sdkman/bin/sdkman-init.sh
else
  echo '/!\ SDKMAN not found, "curl -s https://get.sdkman.io | bash"'
fi

# enable zsh plugins
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
# this plugin must be the last to be sourced
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
