- package:
    name: "{{ item }}"
    state: present
  with_items:
  - git
  - tk # add support for git gui
  become: yes

- template:
    src: git/{{ item }}
    dest: ~/.{{ item }}
    mode: 0444
  with_items:
  - gitconfig
  - gitignore
