- name: check aur packages are installed
  aur_package:
    name: "{{ item }}"
  with_items:
  - acpi
  - cower
  - i3lock-blur
  - i3-scrot
  - py3status
  - python-pydbus
  - python-tzlocal

- name: install i3 packages
  package:
    name: "{{ item }}"
  with_items:
  - dunst
  - i3-wm
  - python-pytz
  - rofi
  become: yes

- name: install lock script
  template:
    src: lock.sh
    dest: /usr/local/bin/lock
    mode: 0555
  become: yes

- name: create i3 configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - ~/.config
  - ~/.config/i3
  - ~/.config/rofi
  - ~/.config/dunst

- name: configure i3wm
  template:
    src: i3/i3.config
    dest: ~/.config/i3/config
    mode: 0444
  tags:
  - config

- name: configure py3status
  template:
    src: i3/i3status.conf
    dest: ~/.config/i3/i3status.conf
    mode: 0444
  tags:
  - config

- name: install custom scripts for py3status
  template:
    src: i3/fan_status.sh
    dest: ~/.config/i3/fan_status.sh
    mode: 0555
  tags:
  - config

- name: configure rofi
  template:
    src: i3/rofi.config
    dest: ~/.config/rofi/config
    mode: 0444
  tags:
  - config

- name: configure dunst
  template:
    src: dunstrc
    dest: ~/.config/dunst/dunstrc
    mode: 0444
  tags:
  - config

- name: add service to lock screen on suspend
  template:
    src: i3/screen-locker.service
    dest: /etc/systemd/system/
    mode: 0444
  become: yes

- name: enable service to lock screen on suspend
  service:
    name: screen-locker
    enabled: yes
  become: yes

- name: authorize user to manage daemons
  template:
    src: i3/57-allow-passwordless-daemon-management.rules
    dest: /etc/polkit-1/rules.d/57-allow-passwordless-daemon-management.rules
    mode: 0444
  become: yes
