- name: install i3 packages
  package:
    name: "{{ item }}"
  with_items:
  - i3-wm
  - i3lock

- name: check AUR package 'py3status' is installed
  stat:
    path: /usr/bin/py3status
  register: py3status
  failed_when: py3status.stat.exists == False

- name: create i3 configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - ~/.config
  - ~/.config/i3

- name: configure i3wm
  template:
    src: config
    dest: ~/.config/i3/config
    mode: 0444

- name: configure py3status
  template:
    src: i3status.conf
    dest: ~/.config/i3/i3status.conf
    mode: 0444
