- name: check aur packages are installed
  package:
    name: "{{ item }}"
  with_items:
  - acpi
  - cower
  - i3lock-blur
  - py3status
  - python-tzlocal

- name: install i3 packages
  package:
    name: "{{ item }}"
  with_items:
  - i3-wm
  - python-pytz
  - rofi
  become: yes

- name: create i3 configuration directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - ~/.config
  - ~/.config/i3
  - ~/.config/rofi

- name: configure i3wm
  template:
    src: i3/i3.config
    dest: ~/.config/i3/config
    mode: 0444

- name: configure py3status
  template:
    src: i3/i3status.conf
    dest: ~/.config/i3/i3status.conf
    mode: 0444

- name: configure rofi
  template:
    src: i3/rofi.config
    dest: ~/.config/rofi/config
    mode: 0444

