- include: xorg.yml
- include: git.yml
- include: i3wm.yml
- include: intellij.yml

- template:
    src: xinitrc
    dest: ~/.xinitrc
    mode: 0550

- name: install utilities
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - terminator
  - network-manager-applet
  become: yes
