- import_tasks: xorg.yml
- import_tasks: git.yml
- import_tasks: i3wm.yml
- import_tasks: intellij.yml

- template:
    src: xinitrc
    dest: ~/.xinitrc
    mode: 0550

- name: install utilities
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - terminator
  - network-manager-applet
  - gimp
  - go
  - pgadmin4
  - qemu
  - vagrant
  - virtualbox
  - virtualbox-host-dkms
  become: yes
