- name: install xorg packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - xdm-archlinux
  - libglvnd # dep for libgl
  - xf86-video-intel
  - xorg-server
  - xorg-xbacklight
  - xorg-xmodmap
  become: yes

- name: install fonts
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - xorg-fonts-type1
  - ttf-dejavu
  - artwiz-fonts
  - font-bh-ttf
  - font-bitstream-speedo
  - gsfonts
  - nodejs-emojione
  - otf-font-awesome
  - sdl_ttf
  - ttf-bitstream-vera
  - ttf-cheapskate
  - ttf-liberation
  - ttf-freefont
  - ttf-arphic-uming
  - ttf-baekmuk
  become: yes

- name: configure xorg
  template:
    src: xorg/{{ item }}
    dest: /etc/X11/xorg.conf.d/{{ item }}
  with_items:
  - 10-keyboard-layout.conf
  - 10-keyboard-terminate.conf
  become: yes

- name: enable xdm service
  service:
    name: xdm-archlinux
    state: started
    enabled: yes
  become: yes

- name: configure Xresources
  template:
    src: xorg/Xresources
    dest: ~/.Xresources
    mode: 0444

