- hosts: 127.0.0.1
  connection: local
  roles:
  - hp_officejet_pro_8600
  - webcam
  - system
  - macbook_keyboard_fixes
  - networkmanager
  - desktop_environment
  - java
  - zsh
  vars_prompt:
  - name: "ansible_sudo_pass"
    prompt: "Sudo password"
    private: yes
