- import_tasks: pacman.yml
- import_tasks: sound.yml
- import_tasks: networkmanager.yml
- import_tasks: powermanagement.yml
- import_tasks: docker.yml
- import_tasks: ntp.yml
- import_tasks: misc.yml

- name: install system utilities
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - dfc
  - python-virtualenv
  - python2-virtualenv
  - htop
  - httpie
  - intel-ucode
  - iotop
  - openssh
  - rsync
  - vim
  - wireshark-cli
  - wget
  - zip
  - unzip
  - zsh
  become: yes

- name: user group
  group:
    name: "{{ item }}"
  with_items:
  - "{{ username }}"
  - wheel
  become: yes

- name: user profile
  user:
    name: "{{ username }}"
    uid: 1000
    shell: /bin/zsh
    group: "{{ username }}"
    groups: users,network,wheel,video,audio,power,docker,wireshark,sys
  become: yes

- name: configure sudoers
  template:
    src: sudoers
    dest: /etc/sudoers
    mode: 0440
  become: yes
