- package:
    name: networkmanager
    state: installed
  become: yes

- service:
    name: NetworkManager
    state: started
    enabled: yes
  become: yes

- template:
    src: "networkmanager/50-org.freedesktop.NetworkManager.rules"
    dest: /etc/polkit-1/rules.d/
    mode: 0444
  become: yes
