- name: install ntp tools
  package:
    name: ntp
    state: present
  become: yes

- name: configure ntp
  template:
    src: ntp.conf
    dest: /etc/ntp.conf
    mode: 0444
  become: yes
  register: ntpconfig

- name: enable ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
  become: yes

- name: restart fan control service on config change
  service:
    name: mbpfan
    state: restarted
  when: ntpconfig.changed
  become: yes


