- name: enable multilib repository
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
    marker: "# {mark} Ansible managed block"
  register: enable_multilib_source
  become: yes

- name: enable pacman colors
  lineinfile:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
  - { regexp: "^#?Color", line: "Color" }
  - { regexp: "^#?TotalDownload", line: "TotalDownload" }
  - { regexp: "^#?VerbosePkgLists", line: "VerbosePkgLists" }
  - { regexp: "^#?IgnorePkg", line: "IgnorePkg = linux-lts linux-lts-headers" }
  become: yes

- name: update package cache
  package:
    update_cache: yes
  when: enable_multilib_source.changed
  become: yes

- name: configure makepkg
  lineinfile:
    path: /etc/makepkg.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
  - { regexp: "^#?MAKEFLAGS=", line: 'MAKEFLAGS="-j8"' }
  - { regexp: "^#?PKGEXT=", line: "PKGEXT='.pkg.tar'" }
  become: yes

- name: is yay installed? install it manually if it is missing
  command: which yay
  changed_when: false

