- blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
    marker: "# {mark} Ansible managed block"
  register: enable_multilib_source
  become: yes

- package:
    update_cache: yes
  when: enable_multilib_source.changed
  become: yes

- name: configure makepkg
  lineinfile:
    path: /etc/makepkg.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
  - { regexp: "^#?MAKEFLAGS=", line: 'MAKEFLAGS="-j8"' }
  - { regexp: "^#?PKGEXT=", line: "PKGEXT='.pkg.tar'" }
  become: yes

- name: is aurman installed? install it manually if it is missing
  command: which aurman
  changed_when: false

