- name: install power management tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - lm_sensors
  become: yes

- name: install script used by udev rules to disable bluetooth and card reader
  template:
    src: udev/remove_ignore_usb-device.sh
    dest: /usr/local/sbin/remove_ignore_usb-device.sh
    mode: 0555
  become: yes

- name: disable bluetooth and card reader
  template:
    src: udev/{{ item }}
    dest: /etc/udev/rules.d/{{ item }}
    mode: 0444
  with_items:
    - 99-apple_cardreader.rules
    - 99-apple_broadcom_bcm2046_bluetooth.rules
  become: yes

- name: disable systemd powerkey management
  lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^#?HandlePowerKey="
    line: "HandlePowerKey=ignore"
  become: yes

- name: tune sysctl
  template:
    src: sysctl/10-powermanagement.conf
    dest: /etc/sysctl.d/
    mode: 0555
  become: yes
