- name: configure hid apple module
  template:
    src: hid_apple.conf
    dest: /etc/modprobe.d/hid_apple.conf
    mode: 0444
  become: yes

- name: install macbookpro keymap
  template:
    src: fr-macbookpro.map
    dest: /usr/share/kbd/keymaps/i386/azerty/fr-macbookpro.map
    mode: 0444
  become: yes

- name: enable macbookpro keymap
  lineinfile:
    path: /etc/vconsole.conf
    regexp: '^KEYMAP='
    line: 'KEYMAP=fr-macbookpro'
    state: present
  become: yes
